### PR TITLE
Add partial name matching converter for objects

### PR DESCRIPTION
**Pull request by cyrus01337**
End-users always have to type out the full name in order to retrieve whatever Discord-relevant object they want to manipulate and for the bot to manipulate, introducing `PartiallyMatch`.

`PartiallyMatch` is used similarly to `Union` - whatever types you pass are processed conventionally, however if a converter fails then another step is added that attempts to partially match the name and nickname (if present) with the argument passed by the end-user, and if that fails then `Union`'s default behaviour of exhausting all converters is used.

Here is an example cog of how it can be used:
```py
import discord

from utils import DuckCog, DuckContext, command
from utils.converters import PartiallyMatch


class Testing(DuckCog):
    @command()
    async def test(
        self,
        ctx: DuckContext,
        primary: PartiallyMatch[discord.TextChannel],
        secondary: PartiallyMatch[discord.Member, discord.Role],
    ):
        return await ctx.send(f'{primary}, {secondary}')


async def setup(bot):
    await bot.add_cog(Testing(bot))
```

### CODE REVIEW

**Comment by cyrus01337** [comment]
Have yet to apply this to all commands that utilise `Member`/`User` converters, in retrospect there may be a shorter, more util-focused way to approach those specifically as they're used so often.

**Review by LeoCx1000 — CHANGES_REQUESTED** [review]
This seems mostly fine, except that it's missing support for the following converters: 
`discord.abc.GuildChannel`, `discord.ForumChannel`, `discord.StageChannel`.


Also, using `commands.run_converters` instead of manually calling the `.convert()` method and keeping a converter mapping would be ideal, and after that, handle the partial logic inside the `except BadArgument` statement, and re-raise the original conversion error instead of an empty BadArgument.

**Comment by cyrus01337** [comment]
I've included support for  those channels and altered the logic to use Discord.py's conversion logic over my own implementation (thanks for saving me some time there :slightly_smiling_face:).

One other implementation I hadn't considered was case insensitivity. As partial matching is case sensitive by default, I was thinking of including either a new converter for global converter support, or extending the existing functionality.

One idea for the latter was to include a special sentinel that, if included in `PartiallyMatch` e.g. `PartiallyMatch[discord.TextChannel, discord.VoiceChannel, sentinels.CI]`, would ensure all converters match in a case sensitive fashion.

The former seems like a more concrete solution, though I have not considered how this could be implemented and also used in a coherent, comfortable-ish way for DX.

**Comment by LeoCx1000** [comment]
I think making the partial matching be case-insensitive is best since realistically this converter wouldn't be used in any critical commands like ban (that would be dumb). Maybe first check with case-sensitivity then go over them again and do case insensitive matching instead, maybe even fuzzy searching.

**Review by LeoCx1000 — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
