### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by du-cki**
## Summary

Replaced `inspect.Parameter` with `commands.Parameter` when needed, so `discord.py` doesn't raise any errors.

## Checklist

- [x] If code changes were made then they have been tested.
  - [ ] I have updated the docstrings to reflect the changes, if applicable.
- [x] This PR fixes an issue.
- [ ] This PR is **not** a code change.
      *e.g. docstrings, command parameter descriptions, fixing a typo.*
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)

### CODE REVIEW

**Comment by NightSlasher35** [comment]
@du-cki I'm pretty sure the working branch is rewrite, might wanna pr back to that

**Comment by NightSlasher35** [comment]
LGTM

**Comment by du-cki** [comment]
> @du-cki I'm pretty sure the working branch is rewrite, might wanna pr back to that

This issue is relevant to the current instance of the bot (which is on `master`) rather than the `rewrite` branch.

**Comment by NightSlasher35** [comment]
> > @du-cki I'm pretty sure the working branch is rewrite, might wanna pr back to that
> 
> This issue is relevant to the current instance of the bot (which is on `master`) rather than the `rewrite` branch.

I see

**Review by LeoCx1000 — APPROVED** [review]
Thank you.

**Comment by NightSlasher35** [comment]
oh look Leo's alive

**Comment by NightSlasher35** [comment]
I see.

**Pull request merged**
